[workspace]
resolver = "2"
members = [ "crates/*" ]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
iris-core = { path = "crates/iris-core" }
iris-cli = { path = "crates/iris-cli" }

serde = "1.0.229"
serde_json = "1.0.151"
gtk4 = "0.11.5"
gtk4-layer-shell = "0.8.1"
libwayshot = "0.9.0"
image = "0.25.10"
dirs = "7.0.0"
